const STORAGE_KEY='anostosio-job-search-crm-v1';
const LANG_KEY='anostosio-job-search-crm-lang';
const statusKeys=['candidate','preparing','applied','test','interview','offer','rejected','closed'];
const priorityKeys=['veryHigh','high','medium','low'];
const i18n={
  en:{eyebrow:'Job search, without spreadsheet chaos',title:'Track vacancies. See priorities. Move faster.',lead:'A lightweight CRM for applications, match scores, follow-ups and notes. Data stays in your browser and can be exported anytime.',addVacancy:'Add vacancy',export:'Export JSON',import:'Import JSON',search:'Search company, role or notes',pipeline:'Application pipeline',role:'Role',status:'Status',match:'Match',priority:'Priority',salary:'Salary',followup:'Follow-up',focus:'Focus',nextBest:'Next best actions',record:'Vacancy record',company:'Company',matchScore:'Match score',source:'Source',followupDate:'Follow-up date',url:'Vacancy URL',notes:'Notes / match summary',delete:'Delete',cancel:'Cancel',save:'Save vacancy',newVacancy:'New vacancy',editVacancy:'Edit vacancy',allStatuses:'All statuses',allPriorities:'All priorities',sortMatch:'Sort: highest match',sortNewest:'Sort: newest',sortFollowup:'Sort: follow-up',candidate:'Candidate',preparing:'Preparing',applied:'Applied',test:'Test task',interview:'Interview',offer:'Offer',rejected:'Rejected',closed:'Closed',veryHigh:'Very high',high:'High',medium:'Medium',low:'Low',jobs:'vacancies',noResults:'No vacancies match these filters.',total:'Total',active:'Active',appliedStat:'Applied',avgMatch:'Avg. match',today:'Today',overdue:'Overdue',noDate:'No follow-up',open:'Open',edit:'Edit',topMatch:'Top match',topMatchText:'Prioritize {company} — {role} with a {match}% match score.',followups:'Follow-ups',followupsText:'{count} application(s) need follow-up today or are overdue.',pipelineGap:'Pipeline gap',pipelineGapText:'You have {count} active applications before interview. Keep quality high, but add fresh options.',goodPipeline:'Healthy pipeline',goodPipelineText:'You have {count} active opportunities in motion. Focus on follow-ups and interview preparation.',nothingYet:'Start your pipeline',nothingYetText:'Add a few vacancies to see priority recommendations here.',exampleCompany:'Northstar Labs',exampleRole:'Junior AI Automation Specialist',exampleNotes:'Strong fit: AI tools, visual/product thinking, junior-friendly. Need to strengthen APIs and automation examples.'},
  ru:{eyebrow:'Поиск работы без хаоса в таблицах',title:'Вакансии, приоритеты и отклики — в одном месте.',lead:'Лёгкая CRM для вакансий, мэтча, follow-up и заметок. Данные сохраняются в браузере и экспортируются в любой момент.',addVacancy:'Добавить вакансию',export:'Экспорт JSON',import:'Импорт JSON',search:'Поиск по компании, роли или заметкам',pipeline:'Воронка откликов',role:'Вакансия',status:'Статус',match:'Мэтч',priority:'Приоритет',salary:'Зарплата',followup:'Follow-up',focus:'Фокус',nextBest:'Следующие лучшие действия',record:'Карточка вакансии',company:'Компания',matchScore:'Оценка мэтча',source:'Источник',followupDate:'Дата follow-up',url:'Ссылка на вакансию',notes:'Заметки / почему подходит',delete:'Удалить',cancel:'Отмена',save:'Сохранить',newVacancy:'Новая вакансия',editVacancy:'Редактировать вакансию',allStatuses:'Все статусы',allPriorities:'Все приоритеты',sortMatch:'Сортировка: лучший мэтч',sortNewest:'Сортировка: новые',sortFollowup:'Сортировка: follow-up',candidate:'Кандидат',preparing:'Готовлюсь',applied:'Откликнулась',test:'Тестовое',interview:'Собеседование',offer:'Оффер',rejected:'Отказ',closed:'Закрыта',veryHigh:'Очень высокий',high:'Высокий',medium:'Средний',low:'Низкий',jobs:'вакансий',noResults:'По этим фильтрам вакансий нет.',total:'Всего',active:'Активные',appliedStat:'Отклики',avgMatch:'Средний мэтч',today:'Сегодня',overdue:'Просрочено',noDate:'Нет даты',open:'Открыть',edit:'Изменить',topMatch:'Лучший мэтч',topMatchText:'Сфокусируйся на {company} — {role}: мэтч {match}%.',followups:'Follow-up',followupsText:'{count} отклик(а) требуют follow-up сегодня или уже просрочены.',pipelineGap:'Нужно пополнить воронку',pipelineGapText:'Сейчас {count} активных вакансий до этапа собеседования. Добавь свежие варианты, сохраняя качество.',goodPipeline:'Воронка в хорошем состоянии',goodPipelineText:'Сейчас {count} активных возможностей. Основной фокус — follow-up и подготовка к интервью.',nothingYet:'Начни воронку',nothingYetText:'Добавь несколько вакансий, и здесь появятся рекомендации.',exampleCompany:'Northstar Labs',exampleRole:'Junior AI Automation Specialist',exampleNotes:'Сильный мэтч: AI-инструменты, визуальное и продуктовое мышление, junior-friendly. Нужно усилить примеры с API и автоматизацией.'}
};
let lang=localStorage.getItem(LANG_KEY)||'en';
let jobs=loadJobs();
let editingId=null;
const $=id=>document.getElementById(id);
const els={body:$('jobsBody'),stats:$('stats'),insights:$('insights'),count:$('resultCount'),empty:$('emptyState'),dialog:$('jobDialog'),form:$('jobForm'),search:$('searchInput'),statusFilter:$('statusFilter'),priorityFilter:$('priorityFilter'),sort:$('sortSelect')};
function uid(){return crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2)}
function seed(){const today=new Date();const plus=d=>{const x=new Date(today);x.setDate(x.getDate()+d);return x.toISOString().slice(0,10)};return[
{id:uid(),company:'Northstar Labs',role:'Junior AI Automation Specialist',status:'preparing',priority:'veryHigh',match:88,salary:'€1,500–2,000',source:'Geekjob',followup:plus(2),url:'',notes:'Strong entry-level fit. AI tools + product thinking; strengthen API/JSON examples.',createdAt:Date.now()-3000},
{id:uid(),company:'Studio Orbit',role:'AI Product Builder Intern',status:'applied',priority:'high',match:82,salary:'Remote · internship',source:'Young&Junior',followup:plus(0),url:'',notes:'Good bridge from design into AI-assisted product building.',createdAt:Date.now()-2000},
{id:uid(),company:'Flowstack',role:'Junior Automation Builder',status:'candidate',priority:'medium',match:71,salary:'$900–1,300',source:'Career page',followup:'',url:'',notes:'Needs n8n/webhooks confidence. Worth keeping as a stretch role.',createdAt:Date.now()-1000}
]}
function loadJobs(){try{const raw=localStorage.getItem(STORAGE_KEY);return raw?JSON.parse(raw):seed()}catch{return seed()}}
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(jobs))}
function t(key,vars={}){let s=i18n[lang][key]??key;Object.entries(vars).forEach(([k,v])=>s=s.replace(`{${k}}`,v));return s}
function escapeHtml(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function options(select,items,allLabel){select.innerHTML=(allLabel?`<option value="">${allLabel}</option>`:'')+items.map(k=>`<option value="${k}">${t(k)}</option>`).join('')}
function applyLanguage(){document.documentElement.lang=lang;document.querySelectorAll('[data-i18n]').forEach(el=>el.textContent=t(el.dataset.i18n));document.querySelectorAll('[data-i18n-placeholder]').forEach(el=>el.placeholder=t(el.dataset.i18nPlaceholder));$('langToggle').textContent=lang==='en'?'RU':'EN';options(els.statusFilter,statusKeys,t('allStatuses'));options(els.priorityFilter,priorityKeys,t('allPriorities'));els.sort.innerHTML=`<option value="match">${t('sortMatch')}</option><option value="newest">${t('sortNewest')}</option><option value="followup">${t('sortFollowup')}</option>`;options($('status'),statusKeys);options($('priority'),priorityKeys);render()}
function activeJobs(){return jobs.filter(j=>!['rejected','closed'].includes(j.status))}
function renderStats(){const active=activeJobs();const applied=jobs.filter(j=>['applied','test','interview','offer'].includes(j.status)).length;const avg=jobs.length?Math.round(jobs.reduce((a,j)=>a+(Number(j.match)||0),0)/jobs.length):0;els.stats.innerHTML=[['total',jobs.length],['active',active.length],['appliedStat',applied],['avgMatch',`${avg}%`]].map(([k,v])=>`<div class="stat"><span>${t(k)}</span><strong>${v}</strong></div>`).join('')}
function filtered(){const q=els.search.value.trim().toLowerCase();let list=jobs.filter(j=>(!q||[j.company,j.role,j.notes,j.source].join(' ').toLowerCase().includes(q))&&(!els.statusFilter.value||j.status===els.statusFilter.value)&&(!els.priorityFilter.value||j.priority===els.priorityFilter.value));if(els.sort.value==='newest')list.sort((a,b)=>b.createdAt-a.createdAt);else if(els.sort.value==='followup')list.sort((a,b)=>(a.followup||'9999-99-99').localeCompare(b.followup||'9999-99-99'));else list.sort((a,b)=>(b.match||0)-(a.match||0));return list}
function followupLabel(date){if(!date)return t('noDate');const today=new Date().toISOString().slice(0,10);if(date===today)return t('today');if(date<today)return t('overdue');return new Date(date+'T00:00:00').toLocaleDateString(lang==='ru'?'ru-RU':'en-GB',{day:'2-digit',month:'short'})}
function renderTable(){const list=filtered();els.count.textContent=`${list.length} ${t('jobs')}`;els.body.innerHTML=list.map(j=>`<tr><td class="role-cell"><strong>${escapeHtml(j.role)}</strong><span>${escapeHtml(j.company)}${j.source?' · '+escapeHtml(j.source):''}</span></td><td><span class="badge">${t(j.status)}</span></td><td><span class="score">${Number(j.match)||0}%</span></td><td><span class="badge ${j.priority==='veryHigh'||j.priority==='high'?'high':j.priority}">${t(j.priority)}</span></td><td>${escapeHtml(j.salary||'—')}</td><td>${followupLabel(j.followup)}</td><td class="row-actions">${j.url?`<a href="${escapeHtml(j.url)}" target="_blank" rel="noreferrer">↗</a>`:''}<button data-edit="${j.id}" aria-label="${t('edit')}">•••</button></td></tr>`).join('');els.empty.hidden=list.length!==0;els.empty.textContent=t('noResults');els.body.querySelectorAll('[data-edit]').forEach(btn=>btn.addEventListener('click',()=>openDialog(btn.dataset.edit)))}
function renderInsights(){const active=activeJobs();if(!jobs.length){els.insights.innerHTML=`<div class="insight"><strong>${t('nothingYet')}</strong><p>${t('nothingYetText')}</p></div>`;return}const top=[...active].sort((a,b)=>b.match-a.match)[0];const today=new Date().toISOString().slice(0,10);const due=active.filter(j=>j.followup&&j.followup<=today).length;const preInterview=active.filter(j=>['candidate','preparing','applied','test'].includes(j.status)).length;const parts=[];if(top)parts.push(`<div class="insight"><strong>${t('topMatch')}</strong><p>${t('topMatchText',{company:escapeHtml(top.company),role:escapeHtml(top.role),match:top.match})}</p></div>`);parts.push(`<div class="insight"><strong>${t('followups')}</strong><p>${t('followupsText',{count:due})}</p></div>`);parts.push(`<div class="insight"><strong>${t(preInterview<5?'pipelineGap':'goodPipeline')}</strong><p>${t(preInterview<5?'pipelineGapText':'goodPipelineText',{count:preInterview})}</p></div>`);els.insights.innerHTML=parts.join('')}
function render(){renderStats();renderTable();renderInsights()}
function openDialog(id=null){editingId=id;const job=id?jobs.find(j=>j.id===id):null;$('modalTitle').textContent=t(job?'editVacancy':'newVacancy');$('deleteBtn').style.visibility=job?'visible':'hidden';const defaults={company:'',role:'',status:'candidate',priority:'medium',match:70,salary:'',source:'',followup:'',url:'',notes:''};const data=job||defaults;['company','role','status','priority','match','salary','source','followup','url','notes'].forEach(k=>$(k).value=data[k]??'');els.dialog.showModal()}
function closeDialog(){els.dialog.close();editingId=null}
els.form.addEventListener('submit',e=>{e.preventDefault();const data={company:$('company').value.trim(),role:$('role').value.trim(),status:$('status').value,priority:$('priority').value,match:Math.max(0,Math.min(100,Number($('match').value)||0)),salary:$('salary').value.trim(),source:$('source').value.trim(),followup:$('followup').value,url:$('url').value.trim(),notes:$('notes').value.trim()};if(editingId){const idx=jobs.findIndex(j=>j.id===editingId);jobs[idx]={...jobs[idx],...data}}else jobs.unshift({id:uid(),createdAt:Date.now(),...data});save();closeDialog();render()});
$('deleteBtn').addEventListener('click',()=>{if(!editingId)return;jobs=jobs.filter(j=>j.id!==editingId);save();closeDialog();render()});
$('addBtn').addEventListener('click',()=>openDialog());$('closeDialog').addEventListener('click',closeDialog);$('cancelBtn').addEventListener('click',closeDialog);els.dialog.addEventListener('click',e=>{if(e.target===els.dialog)closeDialog()});
[els.search,els.statusFilter,els.priorityFilter,els.sort].forEach(el=>el.addEventListener(el===els.search?'input':'change',render));
$('langToggle').addEventListener('click',()=>{lang=lang==='en'?'ru':'en';localStorage.setItem(LANG_KEY,lang);applyLanguage()});
$('exportBtn').addEventListener('click',()=>{const blob=new Blob([JSON.stringify({version:1,exportedAt:new Date().toISOString(),jobs},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='job-search-crm-export.json';a.click();URL.revokeObjectURL(a.href)});
$('importInput').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;try{const parsed=JSON.parse(await file.text());const incoming=Array.isArray(parsed)?parsed:parsed.jobs;if(!Array.isArray(incoming))throw new Error('invalid');jobs=incoming.map(j=>({...j,id:j.id||uid(),createdAt:j.createdAt||Date.now()}));save();render()}catch{alert(lang==='ru'?'Не удалось импортировать файл.':'Could not import this file.')}e.target.value=''});
applyLanguage();