const copy = {
  en: {
    navToday:'Today',navPipeline:'Pipeline',navAnalyzer:'Analyzer',navAnalytics:'Analytics',navSettings:'Settings',addVacancy:'Add vacancy',version:'v1.0',project:'Project 02 · Job Search CRM',
    todayTitle:'What needs attention now',todayLead:'Opportunities, follow-ups and the next actions that move your search forward.',pipelineTitle:'Application pipeline',pipelineLead:'Move opportunities through clear stages and keep context close to the work.',analyzerTitle:'Vacancy analysis',analyzerLead:"See where the role fits your profile — and where it doesn't.",analyticsTitle:'Search performance',analyticsLead:'Track activity and conversion so effort turns into better decisions.',settingsTitle:'Workspace settings',settingsLead:'Candidate profiles, data safety and local-first preferences.',
    nextBestActions:'Next Best Actions',dueToday:'Due today',overdue:'Overdue follow-ups',waiting:'Waiting for response',needApply:'Need application',upcoming:'Upcoming interviews / tests',strongest:'Strongest opportunity',active:'Active pipeline',applicationsWeek:'Applications this week',noActions:'Nothing urgent right now.',
    board:'Board',table:'Table',archive:'Archive',search:'Search',allStatuses:'All stages',allPriorities:'All priorities',allDirections:'All directions',allModes:'All work modes',allSources:'All sources',allFollowups:'All follow-up states',resetFilters:'Reset filters',highPriority:'High priority',savedFollowUp:'Follow-up',savedDesign:'Design',savedAI:'AI Builder',
    company:'Company',role:'Role',direction:'Direction',status:'Stage',priority:'Priority',match:'Match',source:'Source',location:'Location',workMode:'Work mode',salary:'Salary',followUp:'Follow-up',nextAction:'Next action',openVacancy:'Open vacancy',markApplied:'Mark applied',scheduleFollowUp:'Schedule follow-up',moveInterview:'Move to interview',reviewTest:'Review test task',edit:'Open details',
    candidate:'Candidate',preparing:'Preparing',applied:'Applied',test:'Test task',interview:'Interview',offer:'Offer',rejected:'Rejected',closed:'Closed',veryHigh:'Very high',high:'High',medium:'Medium',low:'Low',remote:'Remote',hybrid:'Hybrid',office:'Office',flexible:'Flexible',unknown:'Unknown',design:'Design',aiBuilder:'AI Builder',brand:'Brand',visual:'Visual',digital:'Digital',other:'Other',
    profile:'Candidate profile',pasteVacancy:'Paste vacancy description',analyze:'Analyze vacancy',addToPipeline:'Add to pipeline',strongSignals:'Strong signals',gaps:'Gaps / risks',hardBlockers:'Hard blockers',recommendation:'Recommendation',breakdown:'Score breakdown',roleDim:'Role relevance',skillsDim:'Skills',formatDim:'Format / geography',levelDim:'Experience level',compensationDim:'Compensation',riskDim:'Risks / constraints',strong:'Strong fit',good:'Good fit',stretch:'Stretch role',weak:'Low fit',applyHigh:'High-priority application',apply:'Worth applying',review:'Review carefully',skip:'Probably skip',
    applications:'Applications',responseRate:'Response rate',interviews:'Interviews',offers:'Offers',pipelineConversion:'Pipeline conversion',sourcePerformance:'Source performance',weeklyActivity:'Weekly application activity',appliedToResponse:'Applied → Response',responseToInterview:'Response → Interview',interviewToOffer:'Interview → Offer',
    profiles:'Candidate Profiles',profileName:'Profile name',targetRoles:'Target roles',strongSkills:'Strong skills',developingSkills:'Developing skills',excludedTasks:'Excluded tasks',preferredMode:'Preferred work mode',allowedGeography:'Allowed geography',salaryMinimum:'Salary minimum',acceptableSeniority:'Acceptable seniority',hardConstraints:'Hard constraints',saveProfile:'Save profile',newProfile:'New profile',dataSafety:'Data & backups',exportJson:'Export JSON',exportCsv:'Export CSV',importBackup:'Import backup',clearWorkspace:'Clear workspace',privacy:'Local-first: vacancy data stays in this browser unless you export it.',
    overview:'Overview',application:'Application',matchTab:'Match',contact:'Contact',notes:'Notes',activity:'Activity',description:'Description',appliedDate:'Applied date',contactName:'Contact name',contactChannel:'Contact channel',rejectionReason:'Rejection reason',strengths:'Strengths',gapsLabel:'Gaps',saveVacancy:'Save vacancy',deleteVacancy:'Delete vacancy',close:'Close',
    vacancyDetail:'Vacancy detail',dangerZone:'Danger zone',confirm:'Confirm',vacancies:'Vacancies',schema:'Schema',fileTooLarge:'Import file is too large.',invalidBackup:'Could not validate this backup.',vacancyPlaceholder:'Paste the vacancy text here...',historyCreated:'Created',historyStageChanged:'Stage changed',historyApplied:'Applied',historyFollowupScheduled:'Follow-up scheduled',historyNoteAdded:'Note added',historyInterview:'Interview',historyTest:'Test task',historyRejected:'Rejected',historyOffer:'Offer',importTitle:'Import backup',importPreview:'Import preview',merge:'Merge',replace:'Replace',cancel:'Cancel',backupBeforeReplace:'A safety backup will be downloaded before Replace.',duplicateTitle:'Possible duplicate',duplicateText:'A similar vacancy already exists.',openExisting:'Open existing',createAnyway:'Create anyway',confirmClear:'Clear all vacancies and local settings?',confirmReplace:'Replace this workspace with the imported backup?',undo:'Undo',deleted:'Vacancy deleted',saved:'Saved',imported:'Backup imported',migrated:'Legacy workspace migrated to schema v3.',
    onboardingTitle:'Build a clear job-search system.',onboardingLead:'Start with an empty workspace, load a clearly marked demo, or restore a backup.',startEmpty:'Start empty',loadDemo:'Load demo workspace',importBackupAction:'Import backup',demoLabel:'Demo',
    emptyPipeline:'No opportunities here yet.',emptyToday:'Your workspace is clear. Add a vacancy or analyze one.',emptyAnalytics:'Analytics will appear after you start moving applications through the pipeline.',notSet:'Not set',today:'Today',overdueLabel:'Overdue',scheduled:'Scheduled',none:'None',from:'from',to:'to',
    footer:'Product concept, UX/UI and front-end by Anostosio°',portfolio:'Portfolio ↗',language:'Language',skip:'Skip to workspace'
  },
  ru: {
    navToday:'Сегодня',navPipeline:'Воронка',navAnalyzer:'Анализ',navAnalytics:'Аналитика',navSettings:'Настройки',addVacancy:'Добавить вакансию',version:'v1.0',project:'Проект 02 · Job Search CRM',
    todayTitle:'Что требует внимания сейчас',todayLead:'Возможности, повторные контакты и следующие действия, которые двигают поиск работы вперёд.',pipelineTitle:'Воронка откликов',pipelineLead:'Перемещай вакансии по понятным этапам и храни контекст рядом с работой.',analyzerTitle:'Анализ вакансии',analyzerLead:'Посмотри, где роль совпадает с профилем — и где есть риски.',analyticsTitle:'Эффективность поиска',analyticsLead:'Следи за активностью и конверсией, чтобы усилия превращались в лучшие решения.',settingsTitle:'Настройки пространства',settingsLead:'Профили кандидата, безопасность данных и local-first настройки.',
    nextBestActions:'Следующие действия',dueToday:'Действия на сегодня',overdue:'Просроченные контакты',waiting:'Ждут ответа',needApply:'Нужно откликнуться',upcoming:'Ближайшие интервью / тестовые',strongest:'Самая сильная возможность',active:'Активная воронка',applicationsWeek:'Отклики за неделю',noActions:'Срочных действий сейчас нет.',
    board:'Доска',table:'Таблица',archive:'Архив',search:'Поиск',allStatuses:'Все этапы',allPriorities:'Все приоритеты',allDirections:'Все направления',allModes:'Все форматы',allSources:'Все источники',allFollowups:'Все повторные контакты',resetFilters:'Сбросить фильтры',highPriority:'Высокий приоритет',savedFollowUp:'Повторный контакт',savedDesign:'Design',savedAI:'AI Builder',
    company:'Компания',role:'Вакансия',direction:'Направление',status:'Этап',priority:'Приоритет',match:'Мэтч',source:'Источник',location:'Локация',workMode:'Формат работы',salary:'Зарплата',followUp:'Повторный контакт',nextAction:'Следующее действие',openVacancy:'Открыть вакансию',markApplied:'Отметить отклик',scheduleFollowUp:'Назначить повторный контакт',moveInterview:'Перевести в интервью',reviewTest:'Открыть тестовое',edit:'Открыть детали',
    candidate:'Кандидат',preparing:'Готовлю отклик',applied:'Отклик отправлен',test:'Тестовое',interview:'Собеседование',offer:'Оффер',rejected:'Отказ',closed:'Закрыта',veryHigh:'Очень высокий',high:'Высокий',medium:'Средний',low:'Низкий',remote:'Удалённо',hybrid:'Гибрид',office:'Офис',flexible:'Гибко',unknown:'Не указано',design:'Дизайн',aiBuilder:'AI Builder',brand:'Брендинг',visual:'Visual',digital:'Digital',other:'Другое',
    profile:'Профиль кандидата',pasteVacancy:'Вставь описание вакансии',analyze:'Анализировать',addToPipeline:'Добавить в воронку',strongSignals:'Сильные сигналы',gaps:'Пробелы / риски',hardBlockers:'Критические ограничения',recommendation:'Рекомендация',breakdown:'Из чего складывается оценка',roleDim:'Соответствие роли',skillsDim:'Навыки',formatDim:'Формат / география',levelDim:'Уровень опыта',compensationDim:'Компенсация',riskDim:'Риски / ограничения',strong:'Сильный мэтч',good:'Хороший мэтч',stretch:'Вакансия на вырост',weak:'Слабый мэтч',applyHigh:'Высокий приоритет — откликаться',apply:'Стоит откликнуться',review:'Проверить внимательнее',skip:'Скорее пропустить',
    applications:'Отклики',responseRate:'Доля ответов',interviews:'Интервью',offers:'Офферы',pipelineConversion:'Конверсия воронки',sourcePerformance:'Эффективность источников',weeklyActivity:'Отклики по неделям',appliedToResponse:'Отклик → Ответ',responseToInterview:'Ответ → Интервью',interviewToOffer:'Интервью → Оффер',
    profiles:'Профили кандидата',profileName:'Название профиля',targetRoles:'Целевые роли',strongSkills:'Сильные навыки',developingSkills:'Развиваемые навыки',excludedTasks:'Исключённые задачи',preferredMode:'Предпочтительный формат',allowedGeography:'Допустимая география',salaryMinimum:'Минимальная зарплата',acceptableSeniority:'Допустимый уровень опыта',hardConstraints:'Жёсткие ограничения',saveProfile:'Сохранить профиль',newProfile:'Новый профиль',dataSafety:'Данные и резервные копии',exportJson:'Экспорт JSON',exportCsv:'Экспорт CSV',importBackup:'Импорт резервной копии',clearWorkspace:'Очистить пространство',privacy:'Local-first: данные вакансий остаются в этом браузере, пока ты сама их не экспортируешь.',
    overview:'Обзор',application:'Отклик',matchTab:'Мэтч',contact:'Контакт',notes:'Заметки',activity:'История',description:'Описание',appliedDate:'Дата отклика',contactName:'Имя контакта',contactChannel:'Канал связи',rejectionReason:'Причина отказа',strengths:'Сильные стороны',gapsLabel:'Пробелы',saveVacancy:'Сохранить вакансию',deleteVacancy:'Удалить вакансию',close:'Закрыть',
    vacancyDetail:'Карточка вакансии',dangerZone:'Опасная зона',confirm:'Подтверждение',vacancies:'Вакансии',schema:'Схема',fileTooLarge:'Файл импорта слишком большой.',invalidBackup:'Не удалось проверить резервную копию.',vacancyPlaceholder:'Вставь сюда текст вакансии...',historyCreated:'Создано',historyStageChanged:'Этап изменён',historyApplied:'Отклик отправлен',historyFollowupScheduled:'Повторный контакт назначен',historyNoteAdded:'Добавлена заметка',historyInterview:'Собеседование',historyTest:'Тестовое',historyRejected:'Отказ',historyOffer:'Оффер',importTitle:'Импорт резервной копии',importPreview:'Предпросмотр импорта',merge:'Объединить',replace:'Заменить',cancel:'Отмена',backupBeforeReplace:'Перед заменой будет скачана страховочная резервная копия.',duplicateTitle:'Возможный дубль',duplicateText:'Похожая вакансия уже есть в CRM.',openExisting:'Открыть существующую',createAnyway:'Создать всё равно',confirmClear:'Очистить все вакансии и локальные настройки?',confirmReplace:'Заменить текущее пространство импортированной резервной копией?',undo:'Отменить',deleted:'Вакансия удалена',saved:'Сохранено',imported:'Резервная копия импортирована',migrated:'Старые данные перенесены в схему v3.',
    onboardingTitle:'Преврати поиск работы в понятную систему.',onboardingLead:'Начни с пустого пространства, загрузи явно помеченное демо или восстанови резервную копию.',startEmpty:'Начать с пустого',loadDemo:'Загрузить демо',importBackupAction:'Импортировать резервную копию',demoLabel:'Демо',
    emptyPipeline:'Здесь пока нет вакансий.',emptyToday:'Пространство чистое. Добавь вакансию или проанализируй её.',emptyAnalytics:'Аналитика появится, когда ты начнёшь двигать отклики по воронке.',notSet:'Не указано',today:'Сегодня',overdueLabel:'Просрочено',scheduled:'Назначено',none:'Нет',from:'из',to:'в',
    footer:'Product concept, UX/UI and front-end by Anostosio°',portfolio:'Portfolio ↗',language:'Язык',skip:'Перейти к рабочей области'
  }
};

export function createTranslator(initial = 'en') {
  let lang = copy[initial] ? initial : 'en';
  return {
    get lang() { return lang; },
    set lang(value) { if (copy[value]) lang = value; },
    t(key, vars = {}) {
      let value = copy[lang][key] ?? copy.en[key] ?? key;
      Object.entries(vars).forEach(([name, replacement]) => { value = String(value).replaceAll(`{${name}}`, String(replacement)); });
      return value;
    }
  };
}
