import {uid,localDateKey} from './date.js';
export const ACTIVE_STATUSES=['candidate','preparing','applied','test','interview','offer'];
export const ALL_STATUSES=[...ACTIVE_STATUSES,'rejected','closed'];
export const PRIORITIES=['veryHigh','high','medium','low'];
export const WORK_MODES=['remote','hybrid','office','flexible'];
export const DIRECTIONS=['design','aiBuilder','other'];
export function clampScore(value){const n=Number(value);return Number.isFinite(n)?Math.min(100,Math.max(0,Math.round(n))):0}
export function normalizeText(value=''){return String(value).trim().toLowerCase().replace(/\s+/g,' ')}
export function sanitizeUrl(value=''){const raw=String(value||'').trim();if(!raw)return '';try{const u=new URL(raw);return ['http:','https:'].includes(u.protocol)?u.href:''}catch{return ''}}
export function normalizedUrl(value=''){const safe=sanitizeUrl(value);if(!safe)return '';const u=new URL(safe);u.hash='';u.searchParams.sort();return u.href.replace(/\/$/,'').toLowerCase()}
export function duplicateOf(candidate,jobs=[],ignoreId=''){const url=normalizedUrl(candidate.url);const company=normalizeText(candidate.company);const role=normalizeText(candidate.role);return jobs.find(j=>j.id!==ignoreId&&((url&&normalizedUrl(j.url)===url)||(company&&role&&normalizeText(j.company)===company&&normalizeText(j.role)===role)))||null}
export function historyEvent(type,details=''){return {id:uid(),type,at:new Date().toISOString(),details:String(details||'')}}
export function createJob(input={}){const now=new Date().toISOString();return normalizeJob({...input,id:input.id||uid(),createdAt:input.createdAt||now,updatedAt:input.updatedAt||now,history:Array.isArray(input.history)&&input.history.length?input.history:[historyEvent('created')]})}
export function normalizeJob(input={}){const status=ALL_STATUSES.includes(input.status)?input.status:'candidate';const priority=PRIORITIES.includes(input.priority)?input.priority:'medium';return {id:String(input.id||uid()),company:String(input.company||'').slice(0,160),role:String(input.role||'').slice(0,200),direction:DIRECTIONS.includes(input.direction)?input.direction:'other',status,priority,matchScore:clampScore(input.matchScore??input.match??0),profileId:String(input.profileId||''),source:String(input.source||'').slice(0,120),url:sanitizeUrl(input.url),location:String(input.location||'').slice(0,180),workMode:WORK_MODES.includes(input.workMode)?input.workMode:'flexible',salary:String(input.salary||'').slice(0,180),description:String(input.description||'').slice(0,12000),notes:String(input.notes||'').slice(0,8000),createdAt:input.createdAt||new Date().toISOString(),updatedAt:input.updatedAt||new Date().toISOString(),appliedAt:String(input.appliedAt||'').slice(0,10),followUpAt:String(input.followUpAt??input.followup??'').slice(0,10),nextAction:String(input.nextAction||'').slice(0,300),contactName:String(input.contactName||'').slice(0,160),contactChannel:String(input.contactChannel||'').slice(0,160),strengths:Array.isArray(input.strengths)?input.strengths.map(String):String(input.strengths||'').split('\n').filter(Boolean),gaps:Array.isArray(input.gaps)?input.gaps.map(String):String(input.gaps||'').split('\n').filter(Boolean),rejectionReason:String(input.rejectionReason||'').slice(0,1000),history:Array.isArray(input.history)?input.history.filter(Boolean).slice(-300):[],isDemo:Boolean(input.isDemo)} }
export function patchJob(job,patch,eventType=''){const next=normalizeJob({...job,...patch,updatedAt:new Date().toISOString()});if(eventType)next.history=[...(job.history||[]),historyEvent(eventType)].slice(-300);return next}
export function markApplied(job,date=localDateKey()){return patchJob(job,{status:'applied',appliedAt:job.appliedAt||date},'applied')}
